model:
  name: EfficientNetV2M-shuffle
  architecture: DeepLabV3plus # Unet
  backbone: EfficientNetV2M
  unfreeze_at: block6a_expand_activation # block4a_expand_activation
  input_shape: [256, 256, 3] # do not change
  output_stride: 32
  filters: [16,32,64,128,256]
  activation: leaky_relu # swish, leaky_relu
  dropout_rate: 0
  pretrained_weights: #/root/Semantic-Segmentation-Cityscapes/pretrained_models/Mapillary/trunk

dataset:
  name: Cityscapes
  path: /mnt/dataset/Cityscapes/
  version: fine
  num_train_images: -1
  num_eval_images: -1
  cache: false
  cache_file: /mnt/dataset/Cityscapes/data_cache
  seed: 80
  input_training: D:/cityscapes/leftImg8bit_trainvaltest/leftImg8bit/train
  label_training: D:/cityscapes/gtFine_trainvaltest/gtFine/train
  max_samples_training: 10000
  input_validation: D:/cityscapes/leftImg8bit_trainvaltest/leftImg8bit/val
  label_validation: D:/cityscapes/gtFine_trainvaltest/gtFine/val
  max_samples_validation: 2000
  one_hot_palette_label: config/labels.py

train_config:
  batch_size: 8
  loss: FocalHybridLoss
  epochs: 2
  final_epochs: 4
  augment: false
  mixed_precision: false # re-validate
  optimizer:
    name: Adam
    weight_decay: 0.00005
    momentum: 0.9
    schedule:
      name: PolynomialDecay
      start_lr: 0.001
      end_lr: 0.0001
      decay_epochs: 10
      power: 2
  distribute:
    strategy: MirroredStrategy #ParameterServerStrategy # NOT IMPEMENTED
    devices: ["GPU:0", "GPU:1"] # NOT IMPEMENTED

eval_config:
  eval_scales: [0.5, 1, 2] # NOT IMPEMENTED
  output_stride: 16 # NOT IMPEMENTED

inference_config:
  precision: float32 # NOT IMPEMENTED
  output_stride: 16 # NOT IMPEMENTED

logs_dir: # NOT IMPEMENTED